cs235 Website (database implementation)/music/blueprints/body.py
from flask import Blueprint, redirect, render_template, url_for, request

from music.domainmodel.track import Track
import music.adapters.repository as repo
import random

body_blueprint = Blueprint('body_bp', __name__)
track = repo.repo_instance

def create_some_track():
    num_items = track.get_num_tracks()
    index = random.randint(0, num_items)
    some_track = track.get_track_by_id(index)
    while some_track is None:
        index = random.randint(0, num_items)
        some_track = track.get_track_by_id(index)
    return some_track


@body_blueprint.route('/')
def body():
    some_track = create_some_track()
    logged_in = False
    if request.cookies.get('User') is not None:
        logged_in = True
    return render_template('body/body.html', track=some_track, logged_in=logged_in)

cs235 Website (database implementation)/music/blueprints/track.py
from flask import Blueprint, redirect, render_template, url_for, request
from flask_wtf import FlaskForm
from wtforms import IntegerField, SubmitField
from wtforms.validators import DataRequired


import music.adapters.repository as repo

import random, math

track_blueprint = Blueprint('track_bp', __name__)
database = repo.repo_instance


def create_some_track():
    num_items = database.get_num_tracks()
    index = random.randint(0, num_items)
    some_track = database.get_track_by_id(index)
    while some_track is None:
        index = random.randint(0, num_items)
        some_track = database.get_track_by_id(index)
    return some_track


@track_blueprint.route('/track')
def list_track():
    some_track = create_some_track()
    track_message = ''
    logged_in = False
    if request.cookies.get('User') is not None:
        logged_in = True
    return render_template('track_list.html', track=some_track, message=track_message, logged_in=logged_in)


@track_blueprint.route('/tracks/<int:index>', methods=['POST', 'GET'])
def success(index):
    form = PageView()
    list_of_tracks = database.get_track_list()
    track_length = database.get_num_tracks()
    some_track = create_some_track()
    new_track_list = []
    index = index*10
    previous_index = index-10
    for i in range(previous_index, index):
        if i < track_length:
            new_track_list.append(list_of_tracks[i])
        else:
            break
    if request.form.get('back') is not None:
        if index != 1:
            index = int((index / 10)-1)
            return redirect(url_for('track_bp.success', index=index))
    elif request.form.get('forward') is not None:
        if index != 1:
            index = int((index / 10)+1)
            return redirect(url_for('track_bp.success', index=index))
    return render_template('track_list_all.html', form=form, handler_url=int(index/10), track=some_track, track_list=new_track_list)


@track_blueprint.route('/block_choice', methods=['POST', 'GET'])
def list_some_tracks():
    track_length = database.get_num_tracks()
    page_num = int(math.ceil(track_length/10))
    some_track = create_some_track()
    form = ListSome()
    if request.method == 'POST':
        return redirect(url_for('track_bp.success', index=int(request.form.get('index'))))
    else:
        return render_template('track_list_some.html', form=form, handler_url="block_choice", track=some_track, amount=page_num)


@track_blueprint.route('/track_find/<int:track_id>', methods=['POST', 'GET'])
def track_viewer_id(track_id):
    some_track = create_some_track()
    tracks = database.get_track_list()
    track_message = ''
    for track in tracks:
        if track_id == track.track_id:
            review_list = database.get_review_by_track(track_id)
            user_list = database.get_user_by_track(track_id)
            return render_template("track_view.html", artist=track.artist.full_name, song=track.title, album=track.album.title, url=track.track_url, duration=track.track_duration, reviews=review_list, users=user_list, track=some_track)
        else:
            track_message = "Track with specified ID doesn't exist"

    return render_template('track_list.html', track=tracks, message=track_message)


@track_blueprint.route('/track_find_artist/<artist_name>', methods=['POST', 'GET'])
def track_viewer_artist(artist_name):
    new_track_list = []
    form = PageView()
    tracks = database.get_track_list()
    some_track = create_some_track()
    for track in tracks:
        if artist_name == track.artist.full_name:
            new_track_list.append(track)
    return render_template('track_list_all.html', form=form, handler_url=artist_name, track=some_track, track_list=new_track_list)


@track_blueprint.route('/track_find_track/<track_title>', methods=['POST', 'GET'])
def track_viewer_title(track_title):
    new_track_list = []
    tracks = database.get_track_list()
    form = PageView()
    some_track = create_some_track()
    for track in tracks:
        if track.title is not None:
            if track_title == track.title:
                new_track_list.append(track)
    return render_template('track_list_all.html', form=form, handler_url=track_title, track=some_track, track_list=new_track_list)


@track_blueprint.route('/track_find_genre/<genre_name>', methods=['POST', 'GET'])
def track_viewer_genre(genre_name):
    new_track_list = []
    tracks = database.get_track_list()
    form = PageView()
    some_track = create_some_track()
    genre_found = False
    for track in tracks:
        genres_list = track.genres
        for genre in genres_list:
            if genre.name == genre_name:
                new_track_list.append(track)
                genre_found = True
                break
    if not genre_found:
        logged_in = False
        if request.cookies.get('User') is not None:
            logged_in = True
        return render_template('track_list.html', track=some_track, message="No tracks found with specified genre", logged_in=logged_in)
    return render_template('track_list_all.html', form=form, handler_url=genre_name, track=some_track, track_list=new_track_list)


@track_blueprint.route('/find', methods=['GET', 'POST'])
def find_track():
    some_track = create_some_track()
    tracks = database.get_track_list()
    form = SearchForm()
    if form.validate_on_submit():
        if form.id.data is not None:
            return redirect(url_for("track_bp.track_viewer_id", track_id=int(form.id.data)))
        elif request.form.get('artist') is not None:
            return redirect(url_for("track_bp.track_viewer_artist", artist_name=request.form.get('artist')))
        elif request.form.get('track_name') is not None:
            return redirect(url_for("track_bp.track_viewer_title", track_title=request.form.get('track_name')))
        elif request.form.get('genre_name') is not None:
            return redirect(url_for("track_bp.track_viewer_genre", genre_name=request.form.get('genre_name')))

        else:
            return render_template("track_search.html", form=form, handler_url="find", track=some_track, track_list=tracks)
    else:
        return render_template("track_search.html", form=form, handler_url="find", track=some_track, track_list=tracks)


class SearchForm(FlaskForm):
    # id = IntegerField("<name>", [DataRequired(message="You need to use an ID")])
    id = IntegerField("Search by ID")
    submit = SubmitField("Submit")


class ListSome(FlaskForm):
    submit = SubmitField("Submit")


class PageView(FlaskForm):
    back = SubmitField("<-")
    forward = SubmitField("->")

cs235 Website (database implementation)/music/blueprints/user.py
from flask import Blueprint, redirect, render_template, url_for, make_response, request
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired, Length

from music.domainmodel.user import User
from music.domainmodel.review import Review
import music.adapters.repository as repo
import random

user_blueprint = Blueprint('user_bp', __name__)
database = repo.repo_instance

def create_some_track():
    num_items = database.get_num_tracks()
    index = random.randint(0, num_items)
    some_track = database.get_track_by_id(index)
    while some_track is None:
        index = random.randint(0, num_items)
        some_track = database.get_track_by_id(index)
    return some_track


@user_blueprint.route('/register', methods=['GET', 'POST'])
def register():
    some_track = create_some_track()
    number_of_entries = database.get_number_of_users()
    form = UserForm()
    message = ""
    if form.validate_on_submit():
        user_id = number_of_entries+1
        username = form.username.data
        password = form.password.data
        user_in_db = database.get_user(username.lower())
        if user_in_db is None:
            new_user = User(user_id, username, password)
            database.add_user(new_user)
            message = "User registered, navigate to login to login."
            return render_template('track_list.html', track=some_track, message=message)
        else:
            message = "Username already exists, please choose another."
    return render_template('user_access.html', form=form, handler_url="register", track=some_track, message=message, title="Register")


@user_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    some_track = create_some_track()
    resp = make_response(redirect(url_for("body_bp.body")))
    form = UserForm()
    message = ""
    if form.validate_on_submit():
        username = form.username.data.lower()
        login_password = form.password.data
        user = database.get_user(username)
        message = "User doesn't exist"
        if user is not None:
            if login_password == user.password:
                resp.set_cookie('User', user.user_name)
                return resp
    return render_template('user_access.html', form=form, handler_url="login", track=some_track, message=message, title="Login")


@user_blueprint.route('/logout')
def logout():
    resp = make_response(redirect(url_for("body_bp.body")))
    user = request.cookies.get('User')
    if user is not None:
        resp.set_cookie('User', user, expires=0)
    return resp


@user_blueprint.route('/user_review', methods=['GET', 'POST'])
def write_review():
    tracks = database.get_track_list()
    username = request.cookies.get('User')
    if username is None:
        return redirect(url_for("track_bp.list_track"))
    some_track = create_some_track()
    form = ReviewForm()
    if form.validate_on_submit():
        review = form.review.data
        track_info = request.form.get('track_name')
        track_id = track_info.split(" ")[-1].split(">")[0]
        track = database.get_track_by_id(int(track_id))
        rating = int(request.form.get('rating'))
        if review is not None and track is not None and rating is not None:
            new_review = Review(track, review, rating)
            user = database.get_user(username)
            database.add_review(new_review)
            database.add_user_to_review(review, user)
            return render_template('track_list.html', track=some_track, message="Review successfully added")

    return render_template('review_write.html', form=form, handler_url="user_review", track=some_track, track_list=tracks)


class UserForm(FlaskForm):
    username = StringField("username", [DataRequired(message="Please enter a Username")])
    password = StringField("password", [Length(min=7)])
    submit = SubmitField("Submit")


class ReviewForm(FlaskForm):
    review = StringField("Review:", [DataRequired(message="Please enter a Review")])
    submit = SubmitField("Submit")

cs235 Website (database implementation)/music/templates/header.html
<header id="header">
    <div class="span_1_of_3" id="left">e</div>
    <div class="span_2_of_3" id="right">egg</div>
  </header>
  

cs235 Website (database implementation)/music/templates/layout.html
<!DOCTYPE html>

<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Music heaven 2022</title>

    <link rel="stylesheet" href={{ url_for("static", filename="css/main.css")
}}>

  <body>
    <div class="container">

      <div class="span_3_of_3" id="nav">
        <!-- Include navigation partial. -->
        {% include 'navigation.html' %}
      </div>
  
      <div class="span_3_of_3" id="head">
        <!-- Include header partial. -->
        <!-- {% include 'header.html' %} -->
      </div>

      <div class="span_2_of_3" id="content">
        <!-- Main content block to be supplied by page. -->
        {% block content %} {% endblock %}
      </div>

      <div class="span_1_of_3" id="extra">
        <!-- Include sidebar partial. -->
        {% include 'simple_track.html' %}
      </div>
      
      <div class="span_3_of_3" id="footer">
        <div id="footer_content">
          <p>COMPSCI 235 Software Development Methodologies</p> 
        </div>
      </div>

    </div>
  </body>
</html>

cs235 Website (database implementation)/music/templates/navigation.html
<nav id="nav">
  
    <h2 id="nav-header">
      <p style="font-size: 45px;">Music heaven</p>
      <p style="font-size: 20px;">Where you can find all your musical needs</p>
    </h2>
    <div id="nav-links">
        <ul>
            <li><a class="btn-nav" href="{{ url_for('body_bp.body') }}">Home</a></li>
            <li><a class="btn-nav" href="{{ url_for('track_bp.list_track') }}">Tracks</a></li>
            <div style="float: right;">
              <li><a class="btn-nav" href="{{ url_for('user_bp.register') }}">Register</a></li>
              <li><a class="btn-nav" href="{{ url_for('user_bp.login') }}">Login</a></li>
              {% if logged_in %}
                <li><a class="btn-nav" href="{{ url_for('user_bp.logout') }}">Logout</a></li>
              {% endif %}
            </div>
            
        </ul>
    </div>
    
  </nav>
  

cs235 Website (database implementation)/music/templates/review_write.html
{% extends 'layout.html' %} {% block content %}
<div id="track_list">
  <div>
    <form method="POST" action="{{ handler_url }}">
      {{ form.csrf_token }}
      <div>{{ form.review.label }} {{ form.review }}</div>
      
      {% set check_list_title = [] %}
      <select name="track_name">
        <option selected disabled>Select Song</option>
        {% for track in track_list %}
        {% set track_title = track.title %}
        {% if track_title not in check_list_title %}
          {{ check_list_title.append(track_title) }}
          <option value="{{ track }}">Track title: "{{ track_title }}" ||| Album title: "{{ track.album.title }}"</option>
        {% endif %}
        {% endfor %}
      </select>
      </br>
      
      <select name="rating">
        <option selected disabled>Rating</option>
        <option value="1">&#9733; &#9734; &#9734; &#9734; &#9734;</option>
        <option value="2">&#9733; &#9733; &#9734; &#9734; &#9734;</option>
        <option value="3">&#9733; &#9733; &#9733; &#9734; &#9734;</option>
        <option value="4">&#9733; &#9733; &#9733; &#9733; &#9734;</option>
        <option value="5">&#9733; &#9733; &#9733; &#9733; &#9733;</option>
      </select>
      </br>
      
      {{ form.submit }}
    </form>
  </div>
</div>
{% endblock %}

cs235 Website (database implementation)/music/templates/simple_track.html
<body>
    <div id="track">
        <h1>Random track from albums</h1>
        <h2>Title: {{ track.title }}</h2>
        <p>Track Duration: <b>{{ track.track_duration }}</b> seconds</p>
        <p>Track URL: <i>{{ track.track_url }}</i></p>
    </div>
</body>

cs235 Website (database implementation)/music/templates/track_list.html
{% extends 'layout.html' %} {% block content %}

<div id="track_list_navi">
  <ul id="track_ul">
    <li><a class="btn-nav" href="{{ url_for('track_bp.success', index=1) }}">View tracks</a></li>
    <li><a class="btn-nav" href="{{ url_for('track_bp.find_track') }}">Find a specific track</a></li>
    {% if logged_in %}
      <li><a class="btn-nav" href="{{ url_for('user_bp.write_review') }}">Write a review for a track</a></li>
    {% endif %}
  </ul>
</div>
<div>
  <p id="error_message">{{ message }}</p>
</div>
{% endblock %}

cs235 Website (database implementation)/music/templates/track_list_all.html
{% extends 'layout.html' %} {% block content %}

<div id="track_list">

  <div id="track_list_navi">
    <div class="page_view">
      <form method="POST" action="{{ handler_url }}">
        {{ form.csrf_token }}
        <select name="back" hidden>
          <option selected value="0"></option>
        </select>
        <button type="submit">&#8592;</button>
      </form>
    </div>

    <ul id="track_ul">
      <li><a class="btn-nav" href="{{ url_for('track_bp.list_some_tracks') }}">Select page of tracks</a></li>
    </ul>

    <div class="page_view">
      <form method="POST" action="{{ handler_url }}">
        <form method="POST" action="{{ handler_url }}">
          {{ form.csrf_token }}
          <select name="forward" hidden>
            <option selected value="0"></option>
          </select>
          <button type="submit">&#8594;</button>
        </form>
      </form>
    </div>
  </div>
  
  <table>
    <tr>
      <th>Artist</th>
      <th>Album</th>
      <th>Song/Title</th>
      <th>Url</th>
      <th>Duration</th>
      <th>View</th>
    </tr>
    {% for tracks in track_list %}
    <tr>
      <td>{{ tracks.artist.full_name }}</td>
      <td>{{ tracks.album.title }}</td>
      <td>{{ tracks.title }}</td>
      <td style="width: 2px;">{{ tracks.track_url }}</td>
      <td>{{ tracks.track_duration }}</td>
      
      <td>
        {% set track_info_id = tracks.track_id %}
        <form method="POST" action="{{ url_for('track_bp.track_viewer_id', track_id=track_info_id) }}">
          {{ form.csrf_token }}
          <select name="track" hidden>
              <option value="{{ track_info_id }}"></option>
          </select>
          <button type="submit">View Track</button>
        </form>
      </td>

    </tr>
    {% endfor %}
  </table>
</div>
{% endblock %}

cs235 Website (database implementation)/music/templates/track_list_some.html
{% extends 'layout.html' %} {% block content %}

<div id="track_list">
  <form method="POST" action="{{ handler_url }}">
    {{ form.csrf_token }}
    <select name="index">
      <option selected>Select page Number</option>
      {% for index in range(amount) %}
      {% if index != 0 %}
        <option value="{{ index }}">{{ index }}</option>
      {% endif %}
      {% endfor %}
    </select>
    <button type="submit">Submit</button>
  </form>
</div>
{% endblock %}

cs235 Website (database implementation)/music/templates/track_search.html
{% extends 'layout.html' %} {% block content %}
<div id="track_list">
  <div>
    <form method="POST" action="{{ handler_url }}">
      {{ form.csrf_token }}
      <div>{{ form.id.label }} {{ form.id }} {{ form.submit }}</div>
    </form>
  </div>
  
  <div>
    <form method="POST" action="{{ handler_url }}">
      {{ form.csrf_token }}
      {% set check_list_artist = [] %}
      <select name="artist">
        <option selected disabled>Select Artist</option>
        {% for track in track_list %}
        {% set artist = track.artist.full_name %}
          {% if artist not in check_list_artist %}
            {{ check_list_artist.append(artist) }}
            <option value="{{ artist }}">{{ artist }}</option>
          {% endif %}
        {% endfor %}
      </select>
      <button type="submit">Submit</button>
    </form>
  </div>
  
  <div>
    <form method="POST" action="{{ handler_url }}">
      {{ form.csrf_token }}
      {% set check_list_title = [] %}
      <select name="track_name">
        <option selected disabled>Select Track</option>
        {% for track in track_list %}
          {% set track_name = track.title %}
          {% if track_name not in check_list_title %}
            {{ check_list_title.append(track_name) }}
            <option value="{{ track_name }}">{{ track_name }}</option>
          {% endif %}
        {% endfor %}
      </select>
      <button type="submit">Submit</button>
    </form>
  </div>

  <div>
    <form method="POST" action="{{ handler_url }}">
      {{ form.csrf_token }}
      {% set check_list_genre = [] %}
      <select name="genre_name">
        <option selected disabled>Select Genre</option>
        {% for track in track_list %}
          {% set genre_list = track.genres %}
          {% for genre in genre_list %}
            {% if genre not in check_list_genre %}
              {{ check_list_genre.append(genre) }}
              {% set genre_title = genre.name %}
              <option value="{{ genre_title }}">{{ genre_title }}</option>
            {% endif %}
          {% endfor %}
        {% endfor %}
      </select>
      <button type="submit">Submit</button>
    </form>
  </div>
</div>
{% endblock %}

cs235 Website (database implementation)/music/templates/track_view.html
{% extends 'layout.html' %} {% block content %}
<main id="main">
  <h1>Title: {{ song }}</h1>
  <h2>Album: {{ album }}</h2>
  <h3>Artist: {{ artist }}</h3>
  <p>Track Duration: <b>{{ duration }}</b> seconds</p>
  <p>Track URL: <i><a href="{{ url }}">{{ url }}</a></i></p>
  <div id="review">
    <table>
      <tr>
        <th>User</th>
        <th>Review</th>
        <th>Rating</th>
      </tr>
      {% for review in range(reviews|length) %}
        <tr>
          {% if review < users|length %}
            <td>{{ users[review].user_name }}</td>
          {% else %}
            <td>User Removed</td>
          {% endif %}

          <td>{{ reviews[review].review_text }}</td>
          <td>{{ reviews[review].rating }}</td>
        </tr>
      {% endfor %}
    </table>
  </div>
</main>
{% endblock %}

cs235 Website (database implementation)/music/templates/user_access.html
{% extends 'layout.html' %} {% block content %}
<div id="track_list">
  <div>
    <h1>{{ title }}</h1>
    <form method="POST" action="{{ handler_url }}">
      {{ form.csrf_token }}
      <div>{{ form.username.label }} {{ form.username }}</div>
      <div>{{ form.password.label }} {{ form.password }}</div>
      {{ form.submit }}
    </form>
    <p>{{ message }}</p>
  </div>
</div>
{% endblock %}